{
 "title": "Ovs Exporter",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "数据源", "query": "Prometheus" },
   { "name": "job", "label": "JOB", "query": "openvswitch" },
   {
    "name": "instance",
    "label": "主机名",
    "query": {
     "query": "label_values(ovs_info{job=~\"$job\"}, instance)"
    }
   },
   {
    "name": "ovs_interface_name",
    "label": "端口名",
    "query": {
     "query": "label_values(ovs_interface{instance=~\"$instance\",job=~\"$job\"}, name)"
    }
   },
   { "name": "interval", "label": "时间间隔", "query": "30s,1m,2m,3m,5m,10m,30m" },
   {
    "name": "ovs_interface_uuid",
    "label": "端口uuid",
    "query": {
     "query": "label_values(ovs_interface{instance=~\"$instance\",job=~\"$job\"}, uuid)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "ovs version",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ovs_info{hostname=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "网桥的接口总数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(ovs_dp_br_if_total{instance=~\"$instance\", job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "端口-pod映射表",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "ovs_interface{instance=~\"$instance\", job=~\"$job\",uuid=~\"$ovs_interface_uuid\"} - 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "ovs_interface_external_ids{instance=~\"$instance\", job=~\"$job\",uuid=~\"$ovs_interface_uuid\", key=\"pod-id\"} - 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "流表条数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(ovs_flowtable_count{instance=~\"$instance\", job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "端口列表",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "ovs_dp_if{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "主机名"
    }
   ]
  },
  {
   "title": "OVS接口发送的字节数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ovs_interface_tx_bytes{instance=~'$instance',job=~\"$job\",uuid=~\"$ovs_interface_uuid\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "OVS接口接收的字节数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ovs_interface_rx_bytes{instance=~'$instance',job=~\"$job\",uuid=~\"$ovs_interface_uuid\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "OVS接口发送的字节数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ovs_interface_tx_bytes{instance=~'$instance',job=~\"$job\",uuid=~\"$ovs_interface_uuid\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "OVS接口接收的报文数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ovs_interface_rx_packets{instance=~'$instance',job=~\"$job\",uuid=~\"$ovs_interface_uuid\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "OVS接口丢弃的输入包数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ovs_interface_rx_dropped{instance=~'$instance',job=~\"$job\",uuid=~\"$ovs_interface_uuid\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "OVS接口丢弃的输出包数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ovs_interface_tx_dropped{instance=~'$instance',job=~\"$job\",uuid=~\"$ovs_interface_uuid\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "OVS接口接收到的报文的CRC错误数",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ovs_interface_rx_crc_err{instance=~'$instance',job=~\"$job\",uuid=~\"$ovs_interface_uuid\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  }
 ]
}